### Programming Exercise 1: Linear Regression

#### Warmup Excercise : Return the 5x5 identity matrix 

In [1]:
import numpy as np

In [20]:
def WarmUpExercise():
    return np.matrix(np.identity(5, dtype=int))  # the np.matrix is not recommended

In [21]:
A=WarmUpExercise()

In [22]:
A

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

In [ ]:
# use np.eye, by default get the same identity square matrix
np.eye(5)

In [14]:
# non-squred matrix
np.eye(5,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# move diagnal one row up
np.eye(5,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [19]:
# move diagnal one row down
np.eye(5,3,-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

###  Linear regression with one variable

In this part of this exercise, you will implement linear regression with one
variable to predict profits for a food truck. Suppose you are the CEO of a
restaurant franchise and are considering different cities for opening a new
outlet. The chain already has trucks in various cities and you have data for
profits and populations from the cities.

#### Load Data

The file ex1data1.txt contains the dataset for our linear regression problem.
The first column is the population of a city and the second column is
the profit of a food truck in that city. A negative value for profit indicates a
loss.

#### Plotting Data